name: 'Debug Python'
description: 'Installs Python with Debug Extensions'
inputs:
  python-version:
    description: 'Python version to build'
    required: true
  xvfb_command:
    description: 'Command to run for xvfb in order to run tests headless in Linux'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Cache (Python)
      uses: actions/cache@v2.1.7
      id: cache-python
      with:
        path: $RUNNER_TOOL_CACHE/Python/
        key: '${{ runner.os }}-PythonCache-v${{ inputs.python-version }}-dbg'

    - name: Download Python
      if: steps.cache-python.outputs.cache-hit != 'true'
      uses: carlosperate/download-file-action@v1.0.3
      id: download-python
      with:
       file-url: 'https://www.python.org/ftp/python/${{ inputs.python-version }}/Python-${{ inputs.python-version }}.tar.xz'
       file-name: 'Python-${{ inputs.python-version }}.tar.xz'
       location: '${{ runner.workspace }}/dl/'

    - name: Enable Source Repository
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: |
        sudo sed -i '/deb-src/s/^# //' /etc/apt/sources.list
      shell: bash

    - name: Install Build Dependencies
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: >
        sudo apt-get update -qq && sudo apt-get build-dep python3 && sudo apt-get install -qq pkg-config
        build-essential gdb lcov libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev
        libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev
        lzma lzma-dev tk-dev uuid-dev zlib1g-dev
      shell: bash

    - name: Install Python with Debug
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: |
        cd ${{ runner.workspace }}/dl
        tar -xf Python-${{ inputs.python-version }}.tar.xz
        cd Python-${{ inputs.python-version }}
        ./configure --with-pydebug --prefix=$RUNNER_TEMP/Python/ && make -j && make install
      shell: bash

    - name: Install Python
      run: |
        export PYTHON_FULL_VERSION=${{ inputs.python-version }}
        .github/scripts/setup_debug_python.sh
      shell: bash

    - name: Add Python to path
      run: |
        echo "$RUNNER_TOOL_CACHE/Python/${{ inputs.python-version }}/x64/bin" >> $GITHUB_PATH
        echo "$RUNNER_TOOL_CACHE/Python/${{ inputs.python-version }}/x64" >> $GITHUB_PATH
        echo "$GITHUB_PATH"
      shell: bash

    - name: Display Python version
      run: $RUNNER_TOOL_CACHE/Python/${{ inputs.python-version }}/x64/bin/python -c "import sys; print(sys.version)"
      shell: bash

    - name: Install Poetry
      run: $RUNNER_TOOL_CACHE/Python/${{ inputs.python-version }}/x64/bin/python -m pip install poetry==1.1.11
      shell: bash
    - name: Configure Poetry
      run: poetry config virtualenvs.in-project true
      shell: bash
    - name: Install Python Dependencies
      run: poetry install
      shell: bash
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Test with Pytest
      run: ${{ inputs.xvfb_command }} poetry run poe test-all
      shell: bash
